### PR TITLE
Collapse expand widgets

### PR DESCRIPTION
**Pull request by dulcedilip**
want to have collapse all and expand all functionality at dashboard level,

exposed a function in collapseAll in dashboard.js.

      
       $scope.collapseAll = function(collapseExpandStatus){
          $rootScope.$broadcast('adfDashboardCollapseExapand',{collapseExpandStatus : collapseExpandStatus});
         };

used in widget .js 
      
        $scope.$on("adfDashboardCollapseExapand",function(event,args){
           $scope.widgetState.isCollapsed = args.collapseExpandStatus;
         });

### CODE REVIEW

**Comment by sdorra** [comment]
Thanks. Please do not commit the files in dist, they are only update durring a release.

**Comment by dulcedilip** [comment]
Ok, from next pull request will not push dist files. thank you for updating on this

**Comment by awerlang** [comment]
Nice, but how to open dashboard with all widgets collapsed by default?

**Comment by awerlang** [comment]
To answer my own question:

From widget controller:
```
$scope.$emit('adfDashboardCollapseExapand', { collapseExpandStatus: true });
```

Or from dashboard controller:
```
$rootScope.$applyAsync(() => {
    $rootScope.$broadcast('adfDashboardCollapseExapand', { collapseExpandStatus: true });
});
```

I noticed that widget content is compiled nevertheless, but this is how collapse works.

**Comment by dulcedilip** [comment]
the code which you are discussing is internally to adf framework.

Its upto your requirement how to use collapse all and expand all.
<span class="pull-left widget-title">
     <a href="" title="Collapse Widget" ng-show="options.collapsible &&     widgetState.isCollapsed" ng-click="widgetState.isCollapsed = !widgetState.isCollapsed" class="ng-hide">
     <i class="glyphicon glyphicon-chevron-up"></i>
     </a>
     <a href="" title="Expand Widget" ng-show="options.collapsible && !widgetState.isCollapsed" ng-click="widgetState.isCollapsed = !widgetState.isCollapsed" class="">
     <i class="glyphicon glyphicon-chevron-down"></i>
    </a>
   {{definition.title}}
</span>

**Pull request merged**
