### PR TITLE
add continuous edit mode

### PR DESCRIPTION
**Pull request by luaks**
the idea is to always update the model, not just when exiting edit mode

### CODE REVIEW

**Comment by luaks** [comment]
I've added a few thing to make editing of the model from the outside or via custom views a bit easier

**Comment by sdorra** [comment]
Could you create a new sample, which uses the "continuous edit mode"? We should also document the new attribute for the [api documentation](https://github.com/sdorra/angular-dashboard-framework/blob/master/src/scripts/dashboard.js#L44).

**Comment by luaks** [comment]
Sorry about the late repsonse, I will do so this evening

**Comment by sdorra** [comment]
Thanks.

**Pull request merged**
