### PR TITLE
delete widget in adf

### PR DESCRIPTION
**Pull request by dulcedilip**
Added new delete widget to adf,which prompts user modal popup before he deletes.

    $scope.close = function() {
    var deleteScope= $scope.$new();
    var adfDeleteTemplatePath = adfTemplatePath + 'widget-delete.html';
    if (definition.deleteTemplateUrl) {
    adfEditTemplatePath = definition.deleteTemplateUrl;
    }
     var opts = {
     scope: deleteScope,
    templateUrl: adfDeleteTemplatePath,
    backdrop: 'static'
    };
    var instance = $modal.open(opts);

              deleteScope.closeDialog = function() {
                instance.close();
                deleteScope.$destroy();
              };
              deleteScope.deleteDialog = function() {
                instance.close();
                deleteScope.$destroy();
                var column = $scope.col;
                if (column) {
                  var index = column.widgets.indexOf(definition);
                  if (index >= 0) {
                    column.widgets.splice(index, 1);
                  }
                }
                $element.remove();
              };
        }

### CODE REVIEW

**Comment by sdorra** [comment]
I'm not sure if we need this, because we could always revert a deleted widget with the undo button. Could you add an parameter to the options, for enable/disable this feature? The default value should be disabled for now.

**Comment by dulcedilip** [comment]
My thought process towards this enhancement is before the user deletes directly he will have chance to delete or cancel, instead he need to go to undo the changes as you said, but it increase another click to user. Any way will update the code with above approach.

**Comment by dulcedilip** [comment]
Done.

**Comment by sdorra** [comment]
Thanks

**Pull request merged**
